# Generated by Django 4.2.7 on 2024-09-14 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('name', models.CharField(max_length=50, verbose_name='cinema name')),
                ('location', models.CharField(max_length=100, verbose_name='cinema location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('expense_type', models.CharField(max_length=50, verbose_name='expense type')),
                ('amount', models.IntegerField(verbose_name='expense amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='expense description')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.ImageField(upload_to='movies', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('customers_phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customers phone number')),
                ('seat_number', models.IntegerField(verbose_name='seat number')),
                ('price', models.IntegerField(verbose_name='price')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ticket', to='cinema.movie', verbose_name='movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('ticket_sale', models.IntegerField(verbose_name='ticket sale')),
                ('concession_sale', models.IntegerField(verbose_name='concession sale')),
                ('other_income', models.IntegerField(verbose_name='other income')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='financial_report.tax', verbose_name='tax')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='cinema.ticket', verbose_name='ticket sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('item_name', models.CharField(max_length=50, verbose_name='item name')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('final_amount', models.IntegerField(verbose_name='final amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='financial_report.tax', verbose_name='tax')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
