# Generated by Django 4.2.7 on 2024-09-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('marketing & advertising', 'Marketing & Advertising'), ('utilities', 'Utilities'), ('rent & insurance', 'Rent & Insurance'), ('other', 'Other')], max_length=50, verbose_name='expense type'),
        ),
    ]
