# Generated by Django 4.2.7 on 2024-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='is sold'),
        ),
    ]
