# Generated by Django 4.2.7 on 2024-09-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_expense_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='final_amount',
        ),
    ]
