# Generated by Django 4.2.7 on 2024-09-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_ticket_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='Customers_phone_number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customers_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customers phone number'),
        ),
    ]
