# Generated by Django 4.2.7 on 2024-09-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_inventory_final_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='cinema.ticket', verbose_name='ticket'),
        ),
    ]
