# Generated by Django 4.2.7 on 2024-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_ticket_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
    ]
