# Generated by Django 4.2.7 on 2024-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_revenue_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='other_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='other income'),
        ),
    ]
