# Generated by Django 4.2.7 on 2024-09-12 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_cinema_created_at_alter_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 7, 37, 28, 980812, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 7, 37, 28, 981518, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 7, 37, 28, 982303, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 7, 37, 28, 980266, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
    ]
