# Generated by Django 4.2.7 on 2024-09-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_expense_date_inventory_date_revenue_date_ticket_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
