# Generated by Django 4.2.7 on 2024-09-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0001_initial'),
        ('cinema', '0005_alter_revenue_other_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='financial_report.tax', verbose_name='tax'),
        ),
    ]
