# Generated by Django 4.2.7 on 2024-09-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_expense_date_alter_inventory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='final_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='final income'),
        ),
    ]
