# Generated by Django 4.2.7 on 2024-09-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_revenue_final_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='final_income',
        ),
    ]
