# Generated by Django 4.2.7 on 2024-09-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_revenue_final_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='cinema.cinema', verbose_name='cinema'),
        ),
    ]
