# Generated by Django 4.2.7 on 2024-09-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_revenue_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenue',
            name='cinema',
        ),
    ]
