# Generated by Django 4.2.7 on 2024-09-14 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_remove_ticket_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_sold',
        ),
    ]
