# Generated by Django 4.2.7 on 2024-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employeeperformance',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date created'),
        ),
    ]
