# Generated by Django 4.2.7 on 2024-09-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeperformance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
