# Generated by Django 4.2.7 on 2024-09-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_revenue_cinema'),
        ('employee_management', '0005_alter_employeeperformance_date_alter_payroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema', to='cinema.cinema', verbose_name='workplace'),
        ),
    ]
