# Generated by Django 4.2.7 on 2024-09-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_management', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('profit', models.IntegerField(verbose_name='Profit')),
                ('total_revenue', models.IntegerField(verbose_name='Total Revenue')),
                ('total_expense', models.IntegerField(verbose_name='Total Expense')),
                ('total_taxes', models.IntegerField(verbose_name='Total Taxes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='delete status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='date deleted')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='date restored')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('tax_percentage', models.IntegerField(verbose_name='Tax Percentage')),
                ('tax_type', models.CharField(max_length=50, verbose_name='Tax Type')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_tax', to='employee_management.customuser', verbose_name='Employee')),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_tax', to='cinema.revenue', verbose_name='Revenue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
