# Generated by Django 4.2.7 on 2024-09-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_Report',
            new_name='DailyReport',
        ),
    ]
