# Generated by Django 4.2.7 on 2024-09-12 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0002_alter_dailyreport_created_at_alter_tax_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 7, 37, 28, 974733, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AddField(
            model_name='tax',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 7, 37, 28, 974258, tzinfo=datetime.timezone.utc), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
    ]
