# Generated by Django 4.2.7 on 2024-09-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0003_dailyreport_date_tax_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
