# Generated by Django 4.2.7 on 2024-09-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_report', '0004_alter_dailyreport_date_alter_tax_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(choices=[('employee tax', 'Employee tax'), ('cinema tax', 'Cinema tax')], max_length=50, verbose_name='Tax Type'),
        ),
    ]
